export const paysList = [
  { nom: "Afghanistan", indicatif: "+93", chiffres: 9 },
  { nom: "Afrique du Sud", indicatif: "+27", chiffres: 9 },
  { nom: "Albanie", indicatif: "+355", chiffres: 9 },
  { nom: "Algérie", indicatif: "+213", chiffres: 9 },
  { nom: "Allemagne", indicatif: "+49", chiffres: 10 },
  { nom: "Angola", indicatif: "+244", chiffres: 9 },
  { nom: "Arabie Saoudite", indicatif: "+966", chiffres: 9 },
  { nom: "Argentine", indicatif: "+54", chiffres: 10 },
  { nom: "Australie", indicatif: "+61", chiffres: 9 },
  { nom: "Autriche", indicatif: "+43", chiffres: 10 },
  { nom: "Belgique", indicatif: "+32", chiffres: 9 },
  { nom: "Bénin", indicatif: "+229", chiffres: 8 },
  { nom: "Bolivie", indicatif: "+591", chiffres: 8 },
  { nom: "Brésil", indicatif: "+55", chiffres: 11 },
  { nom: "Bulgarie", indicatif: "+359", chiffres: 9 },
  { nom: "Burkina Faso", indicatif: "+226", chiffres: 8 },
  { nom: "Burundi", indicatif: "+257", chiffres: 8 },
  { nom: "Cameroun", indicatif: "+237", chiffres: 9 },
  { nom: "Canada", indicatif: "+1", chiffres: 10 },
  { nom: "Cap-Vert", indicatif: "+238", chiffres: 7 },
  { nom: "Chili", indicatif: "+56", chiffres: 9 },
  { nom: "Chine", indicatif: "+86", chiffres: 11 },
  { nom: "Chypre", indicatif: "+357", chiffres: 8 },
  { nom: "Colombie", indicatif: "+57", chiffres: 10 },
  { nom: "Congo", indicatif: "+242", chiffres: 9 },
  { nom: "Corée du Sud", indicatif: "+82", chiffres: 10 },
  { nom: "Côte d'Ivoire", indicatif: "+225", chiffres: 10 },
  { nom: "Croatie", indicatif: "+385", chiffres: 9 },
  { nom: "Cuba", indicatif: "+53", chiffres: 8 },
  { nom: "Danemark", indicatif: "+45", chiffres: 8 },
  { nom: "Djibouti", indicatif: "+253", chiffres: 8 },
  { nom: "Egypte", indicatif: "+20", chiffres: 10 },
  { nom: "Emirats Arabes Unis", indicatif: "+971", chiffres: 9 },
  { nom: "Espagne", indicatif: "+34", chiffres: 9 },
  { nom: "Estonie", indicatif: "+372", chiffres: 8 },
  { nom: "Ethiopie", indicatif: "+251", chiffres: 9 },
  { nom: "Finlande", indicatif: "+358", chiffres: 9 },
  { nom: "France", indicatif: "+33", chiffres: 9 },
  { nom: "Gabon", indicatif: "+241", chiffres: 8 },
  { nom: "Gambie", indicatif: "+220", chiffres: 7 },
  { nom: "Ghana", indicatif: "+233", chiffres: 9 },
  { nom: "Grèce", indicatif: "+30", chiffres: 10 },
  { nom: "Guinée", indicatif: "+224", chiffres: 9 },
  { nom: "Guinée-Bissau", indicatif: "+245", chiffres: 7 },
  { nom: "Guinée Equatoriale", indicatif: "+240", chiffres: 9 },
  { nom: "Haïti", indicatif: "+509", chiffres: 8 },
  { nom: "Hongrie", indicatif: "+36", chiffres: 9 },
  { nom: "Inde", indicatif: "+91", chiffres: 10 },
  { nom: "Indonésie", indicatif: "+62", chiffres: 10 },
  { nom: "Irak", indicatif: "+964", chiffres: 10 },
  { nom: "Iran", indicatif: "+98", chiffres: 10 },
  { nom: "Irlande", indicatif: "+353", chiffres: 9 },
  { nom: "Islande", indicatif: "+354", chiffres: 7 },
  { nom: "Israël", indicatif: "+972", chiffres: 9 },
  { nom: "Italie", indicatif: "+39", chiffres: 10 },
  { nom: "Jamaïque", indicatif: "+1876", chiffres: 7 },
  { nom: "Japon", indicatif: "+81", chiffres: 10 },
  { nom: "Jordanie", indicatif: "+962", chiffres: 9 },
  { nom: "Kazakhstan", indicatif: "+7", chiffres: 10 },
  { nom: "Kenya", indicatif: "+254", chiffres: 9 },
  { nom: "Koweït", indicatif: "+965", chiffres: 8 },
  { nom: "Laos", indicatif: "+856", chiffres: 9 },
  { nom: "Liban", indicatif: "+961", chiffres: 8 },
  { nom: "Libye", indicatif: "+218", chiffres: 9 },
  { nom: "Lituanie", indicatif: "+370", chiffres: 8 },
  { nom: "Luxembourg", indicatif: "+352", chiffres: 9 },
  { nom: "Madagascar", indicatif: "+261", chiffres: 9 },
  { nom: "Mali", indicatif: "+223", chiffres: 8 },
  { nom: "Maroc", indicatif: "+212", chiffres: 9 },
  { nom: "Mauritanie", indicatif: "+222", chiffres: 8 },
  { nom: "Mexique", indicatif: "+52", chiffres: 10 },
  { nom: "Moldavie", indicatif: "+373", chiffres: 8 },
  { nom: "Mongolie", indicatif: "+976", chiffres: 8 },
  { nom: "Mozambique", indicatif: "+258", chiffres: 9 },
  { nom: "Namibie", indicatif: "+264", chiffres: 9 },
  { nom: "Niger", indicatif: "+227", chiffres: 8 },
  { nom: "Nigeria", indicatif: "+234", chiffres: 10 },
  { nom: "Norvège", indicatif: "+47", chiffres: 8 },
  { nom: "Nouvelle-Zélande", indicatif: "+64", chiffres: 9 },
  { nom: "Oman", indicatif: "+968", chiffres: 8 },
  { nom: "Ouganda", indicatif: "+256", chiffres: 9 },
  { nom: "Pakistan", indicatif: "+92", chiffres: 10 },
  { nom: "Panama", indicatif: "+507", chiffres: 8 },
  { nom: "Pays-Bas", indicatif: "+31", chiffres: 9 },
  { nom: "Pérou", indicatif: "+51", chiffres: 9 },
  { nom: "Philippines", indicatif: "+63", chiffres: 10 },
  { nom: "Pologne", indicatif: "+48", chiffres: 9 },
  { nom: "Portugal", indicatif: "+351", chiffres: 9 },
  { nom: "Qatar", indicatif: "+974", chiffres: 8 },
  { nom: "République Centrafricaine", indicatif: "+236", chiffres: 8 },
  { nom: "République Démocratique du Congo", indicatif: "+243", chiffres: 9 },
  { nom: "République Dominicaine", indicatif: "+1809", chiffres: 7 },
  { nom: "Roumanie", indicatif: "+40", chiffres: 9 },
  { nom: "Royaume-Uni", indicatif: "+44", chiffres: 10 },
  { nom: "Russie", indicatif: "+7", chiffres: 10 },
  { nom: "Rwanda", indicatif: "+250", chiffres: 9 },
  { nom: "Sénégal", indicatif: "+221", chiffres: 9 },
  { nom: "Serbie", indicatif: "+381", chiffres: 9 },
  { nom: "Sierra Leone", indicatif: "+232", chiffres: 8 },
  { nom: "Singapour", indicatif: "+65", chiffres: 8 },
  { nom: "Slovaquie", indicatif: "+421", chiffres: 9 },
  { nom: "Somalie", indicatif: "+252", chiffres: 8 },
  { nom: "Soudan", indicatif: "+249", chiffres: 9 },
  { nom: "Suède", indicatif: "+46", chiffres: 9 },
  { nom: "Suisse", indicatif: "+41", chiffres: 9 },
  { nom: "Tanzanie", indicatif: "+255", chiffres: 9 },
  { nom: "Tchad", indicatif: "+235", chiffres: 8 },
  { nom: "Thaïlande", indicatif: "+66", chiffres: 9 },
  { nom: "Togo", indicatif: "+228", chiffres: 8 },
  { nom: "Tunisie", indicatif: "+216", chiffres: 8 },
  { nom: "Turquie", indicatif: "+90", chiffres: 10 },
  { nom: "Ukraine", indicatif: "+380", chiffres: 9 },
  { nom: "Uruguay", indicatif: "+598", chiffres: 8 },
  { nom: "Venezuela", indicatif: "+58", chiffres: 10 },
  { nom: "Vietnam", indicatif: "+84", chiffres: 9 },
  { nom: "Yémen", indicatif: "+967", chiffres: 9 },
  { nom: "Zambie", indicatif: "+260", chiffres: 9 },
  { nom: "Zimbabwe", indicatif: "+263", chiffres: 9 },
];