export const paysList = [
  { nom: "Afghanistan", nomEn: "Afghanistan", indicatif: "+93", chiffres: 9 },
  { nom: "Afrique du Sud", nomEn: "South Africa", indicatif: "+27", chiffres: 9 },
  { nom: "Albanie", nomEn: "Albania", indicatif: "+355", chiffres: 9 },
  { nom: "Algérie", nomEn: "Algeria", indicatif: "+213", chiffres: 9 },
  { nom: "Allemagne", nomEn: "Germany", indicatif: "+49", chiffres: 10 },
  { nom: "Angola", nomEn: "Angola", indicatif: "+244", chiffres: 9 },
  { nom: "Arabie Saoudite", nomEn: "Saudi Arabia", indicatif: "+966", chiffres: 9 },
  { nom: "Argentine", nomEn: "Argentina", indicatif: "+54", chiffres: 10 },
  { nom: "Australie", nomEn: "Australia", indicatif: "+61", chiffres: 9 },
  { nom: "Autriche", nomEn: "Austria", indicatif: "+43", chiffres: 10 },
  { nom: "Belgique", nomEn: "Belgium", indicatif: "+32", chiffres: 9 },
  { nom: "Bénin", nomEn: "Benin", indicatif: "+229", chiffres: 8 },
  { nom: "Bolivie", nomEn: "Bolivia", indicatif: "+591", chiffres: 8 },
  { nom: "Brésil", nomEn: "Brazil", indicatif: "+55", chiffres: 11 },
  { nom: "Bulgarie", nomEn: "Bulgaria", indicatif: "+359", chiffres: 9 },
  { nom: "Burkina Faso", nomEn: "Burkina Faso", indicatif: "+226", chiffres: 8 },
  { nom: "Burundi", nomEn: "Burundi", indicatif: "+257", chiffres: 8 },
  { nom: "Cameroun", nomEn: "Cameroon", indicatif: "+237", chiffres: 9 },
  { nom: "Canada", nomEn: "Canada", indicatif: "+1", chiffres: 10 },
  { nom: "Cap-Vert", nomEn: "Cape Verde", indicatif: "+238", chiffres: 7 },
  { nom: "Chili", nomEn: "Chile", indicatif: "+56", chiffres: 9 },
  { nom: "Chine", nomEn: "China", indicatif: "+86", chiffres: 11 },
  { nom: "Chypre", nomEn: "Cyprus", indicatif: "+357", chiffres: 8 },
  { nom: "Colombie", nomEn: "Colombia", indicatif: "+57", chiffres: 10 },
  { nom: "Congo", nomEn: "Congo", indicatif: "+242", chiffres: 9 },
  { nom: "Corée du Sud", nomEn: "South Korea", indicatif: "+82", chiffres: 10 },
  { nom: "Côte d'Ivoire", nomEn: "Ivory Coast", indicatif: "+225", chiffres: 10 },
  { nom: "Croatie", nomEn: "Croatia", indicatif: "+385", chiffres: 9 },
  { nom: "Cuba", nomEn: "Cuba", indicatif: "+53", chiffres: 8 },
  { nom: "Danemark", nomEn: "Denmark", indicatif: "+45", chiffres: 8 },
  { nom: "Djibouti", nomEn: "Djibouti", indicatif: "+253", chiffres: 8 },
  { nom: "Egypte", nomEn: "Egypt", indicatif: "+20", chiffres: 10 },
  { nom: "Emirats Arabes Unis", nomEn: "United Arab Emirates", indicatif: "+971", chiffres: 9 },
  { nom: "Espagne", nomEn: "Spain", indicatif: "+34", chiffres: 9 },
  { nom: "Estonie", nomEn: "Estonia", indicatif: "+372", chiffres: 8 },
  { nom: "Ethiopie", nomEn: "Ethiopia", indicatif: "+251", chiffres: 9 },
  { nom: "Finlande", nomEn: "Finland", indicatif: "+358", chiffres: 9 },
  { nom: "France", nomEn: "France", indicatif: "+33", chiffres: 9 },
  { nom: "Gabon", nomEn: "Gabon", indicatif: "+241", chiffres: 8 },
  { nom: "Gambie", nomEn: "Gambia", indicatif: "+220", chiffres: 7 },
  { nom: "Ghana", nomEn: "Ghana", indicatif: "+233", chiffres: 9 },
  { nom: "Grèce", nomEn: "Greece", indicatif: "+30", chiffres: 10 },
  { nom: "Guinée", nomEn: "Guinea", indicatif: "+224", chiffres: 9 },
  { nom: "Guinée-Bissau", nomEn: "Guinea-Bissau", indicatif: "+245", chiffres: 7 },
  { nom: "Guinée Equatoriale", nomEn: "Equatorial Guinea", indicatif: "+240", chiffres: 9 },
  { nom: "Haïti", nomEn: "Haiti", indicatif: "+509", chiffres: 8 },
  { nom: "Hongrie", nomEn: "Hungary", indicatif: "+36", chiffres: 9 },
  { nom: "Inde", nomEn: "India", indicatif: "+91", chiffres: 10 },
  { nom: "Indonésie", nomEn: "Indonesia", indicatif: "+62", chiffres: 10 },
  { nom: "Irak", nomEn: "Iraq", indicatif: "+964", chiffres: 10 },
  { nom: "Iran", nomEn: "Iran", indicatif: "+98", chiffres: 10 },
  { nom: "Irlande", nomEn: "Ireland", indicatif: "+353", chiffres: 9 },
  { nom: "Islande", nomEn: "Iceland", indicatif: "+354", chiffres: 7 },
  { nom: "Israël", nomEn: "Israel", indicatif: "+972", chiffres: 9 },
  { nom: "Italie", nomEn: "Italy", indicatif: "+39", chiffres: 10 },
  { nom: "Jamaïque", nomEn: "Jamaica", indicatif: "+1876", chiffres: 7 },
  { nom: "Japon", nomEn: "Japan", indicatif: "+81", chiffres: 10 },
  { nom: "Jordanie", nomEn: "Jordan", indicatif: "+962", chiffres: 9 },
  { nom: "Kazakhstan", nomEn: "Kazakhstan", indicatif: "+7", chiffres: 10 },
  { nom: "Kenya", nomEn: "Kenya", indicatif: "+254", chiffres: 9 },
  { nom: "Koweït", nomEn: "Kuwait", indicatif: "+965", chiffres: 8 },
  { nom: "Laos", nomEn: "Laos", indicatif: "+856", chiffres: 9 },
  { nom: "Liban", nomEn: "Lebanon", indicatif: "+961", chiffres: 8 },
  { nom: "Libye", nomEn: "Libya", indicatif: "+218", chiffres: 9 },
  { nom: "Lituanie", nomEn: "Lithuania", indicatif: "+370", chiffres: 8 },
  { nom: "Luxembourg", nomEn: "Luxembourg", indicatif: "+352", chiffres: 9 },
  { nom: "Madagascar", nomEn: "Madagascar", indicatif: "+261", chiffres: 9 },
  { nom: "Mali", nomEn: "Mali", indicatif: "+223", chiffres: 8 },
  { nom: "Maroc", nomEn: "Morocco", indicatif: "+212", chiffres: 9 },
  { nom: "Mauritanie", nomEn: "Mauritania", indicatif: "+222", chiffres: 8 },
  { nom: "Mexique", nomEn: "Mexico", indicatif: "+52", chiffres: 10 },
  { nom: "Moldavie", nomEn: "Moldova", indicatif: "+373", chiffres: 8 },
  { nom: "Mongolie", nomEn: "Mongolia", indicatif: "+976", chiffres: 8 },
  { nom: "Mozambique", nomEn: "Mozambique", indicatif: "+258", chiffres: 9 },
  { nom: "Namibie", nomEn: "Namibia", indicatif: "+264", chiffres: 9 },
  { nom: "Niger", nomEn: "Niger", indicatif: "+227", chiffres: 8 },
  { nom: "Nigeria", nomEn: "Nigeria", indicatif: "+234", chiffres: 10 },
  { nom: "Norvège", nomEn: "Norway", indicatif: "+47", chiffres: 8 },
  { nom: "Nouvelle-Zélande", nomEn: "New Zealand", indicatif: "+64", chiffres: 9 },
  { nom: "Oman", nomEn: "Oman", indicatif: "+968", chiffres: 8 },
  { nom: "Ouganda", nomEn: "Uganda", indicatif: "+256", chiffres: 9 },
  { nom: "Pakistan", nomEn: "Pakistan", indicatif: "+92", chiffres: 10 },
  { nom: "Panama", nomEn: "Panama", indicatif: "+507", chiffres: 8 },
  { nom: "Pays-Bas", nomEn: "Netherlands", indicatif: "+31", chiffres: 9 },
  { nom: "Pérou", nomEn: "Peru", indicatif: "+51", chiffres: 9 },
  { nom: "Philippines", nomEn: "Philippines", indicatif: "+63", chiffres: 10 },
  { nom: "Pologne", nomEn: "Poland", indicatif: "+48", chiffres: 9 },
  { nom: "Portugal", nomEn: "Portugal", indicatif: "+351", chiffres: 9 },
  { nom: "Qatar", nomEn: "Qatar", indicatif: "+974", chiffres: 8 },
  { nom: "République Centrafricaine", nomEn: "Central African Republic", indicatif: "+236", chiffres: 8 },
  { nom: "République Démocratique du Congo", nomEn: "Democratic Republic of Congo", indicatif: "+243", chiffres: 9 },
  { nom: "République Dominicaine", nomEn: "Dominican Republic", indicatif: "+1809", chiffres: 7 },
  { nom: "Roumanie", nomEn: "Romania", indicatif: "+40", chiffres: 9 },
  { nom: "Royaume-Uni", nomEn: "United Kingdom", indicatif: "+44", chiffres: 10 },
  { nom: "Russie", nomEn: "Russia", indicatif: "+7", chiffres: 10 },
  { nom: "Rwanda", nomEn: "Rwanda", indicatif: "+250", chiffres: 9 },
  { nom: "Sénégal", nomEn: "Senegal", indicatif: "+221", chiffres: 9 },
  { nom: "Serbie", nomEn: "Serbia", indicatif: "+381", chiffres: 9 },
  { nom: "Sierra Leone", nomEn: "Sierra Leone", indicatif: "+232", chiffres: 8 },
  { nom: "Singapour", nomEn: "Singapore", indicatif: "+65", chiffres: 8 },
  { nom: "Slovaquie", nomEn: "Slovakia", indicatif: "+421", chiffres: 9 },
  { nom: "Somalie", nomEn: "Somalia", indicatif: "+252", chiffres: 8 },
  { nom: "Soudan", nomEn: "Sudan", indicatif: "+249", chiffres: 9 },
  { nom: "Suède", nomEn: "Sweden", indicatif: "+46", chiffres: 9 },
  { nom: "Suisse", nomEn: "Switzerland", indicatif: "+41", chiffres: 9 },
  { nom: "Tanzanie", nomEn: "Tanzania", indicatif: "+255", chiffres: 9 },
  { nom: "Tchad", nomEn: "Chad", indicatif: "+235", chiffres: 8 },
  { nom: "Thaïlande", nomEn: "Thailand", indicatif: "+66", chiffres: 9 },
  { nom: "Togo", nomEn: "Togo", indicatif: "+228", chiffres: 8 },
  { nom: "Tunisie", nomEn: "Tunisia", indicatif: "+216", chiffres: 8 },
  { nom: "Turquie", nomEn: "Turkey", indicatif: "+90", chiffres: 10 },
  { nom: "Ukraine", nomEn: "Ukraine", indicatif: "+380", chiffres: 9 },
  { nom: "Uruguay", nomEn: "Uruguay", indicatif: "+598", chiffres: 8 },
  { nom: "Venezuela", nomEn: "Venezuela", indicatif: "+58", chiffres: 10 },
  { nom: "Vietnam", nomEn: "Vietnam", indicatif: "+84", chiffres: 9 },
  { nom: "Yémen", nomEn: "Yemen", indicatif: "+967", chiffres: 9 },
  { nom: "Zambie", nomEn: "Zambia", indicatif: "+260", chiffres: 9 },
  { nom: "Zimbabwe", nomEn: "Zimbabwe", indicatif: "+263", chiffres: 9 },
];